before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: QigqPRKrM/jCRxVWA+WtozO7DH95/bLIxlNHRH6c/lnoErmk0ZsIPD7MeBidX92xlkTp6F3IFgi6oi6caqPq4nVssiGbSOjODrimfAGtLEqcU/6PWQPcAiFTaSnQTdvJZQmVzQhRSegfSV4T3AZygIN4JvzfxM2gaekN9mxQT7EtCJgapV5SNHYFE5tJcgvUjnTV8COFrO4UPrpTVGGPm/+vzQKtETDj4Y3hWsRhN+ofYE/ySYuThoGTCyflFQA/SiyDDbi7mKxUSrw/GQ39cW/mQ3/RHzjRTHf0tGZqQ8Mej+sgNttesRCywlS4IGbkEwGXzI86b/EJAZlRuWI1N8RqiefJguad3nl0AD7PLL0m8agZOXIcglJoHl9NTRV1hdUjLn2CGAW+knu/2D7SWXdBvBPWGc/kbTNNFuYgQ8h6a+4Buy+aIGfLsN2LQ12+c4oER29frR8pVsz5T5BWVDhdthHOnEaz0dvM7HMEiwxEN8NdmGVUdrJ6p+9QQq4XHegyLB9oliwMzMiGsNpM1F3eLHMa54vj/bP0zXaqI+iYATL79w1P1Mn/jwEkGLde/Fj1OXau3meH/mhOo6IKiWHRvm1eANI5iC4KgYM+mlVd7zV54wkd54IAKgO1zbyN54tj41H6cyoTl28zXD756IpaHCpCqNGJIc/O9cpRm0g= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
